version: "3.9"
services:
  postgres:
    image: postgres:15.3-alpine3.18
    ports:
      - "15432:5432"
    volumes:
      - "/tmp/diestplan-db-data:/var/lib/postgresql/data"
    env_file:
      - .env

  dienstplan:
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
