version: "3.9"
services:
  postgres:
    image: postgres:14.5-alpine3.16@sha256:db802f226b620fc0b8adbeca7859eb203c8d3c9ce5d84870fadee05dea8f50ce
    volumes:
      - "/tmp/diestplan-db-data:/var/lib/postgresql/data"
    env_file:
      - .env

  dienstplan:
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
