FROM clojure:temurin-25-tools-deps-bookworm-slim
RUN mkdir -p /usr/src/app
COPY deps.edn /usr/src/app/
WORKDIR /usr/src/app
RUN clojure -X:deps prep
RUN clojure -M:dev
COPY . /usr/src/app
CMD ["clojure", "-M:run"]
