site_name: dienstplan
site_description: Slack bot app for duty rotations
site_url: https://dienstplan.readthedocs.io/
copyright: Copyright © Vitaly Samigullin and contributors

repo_url: https://github.com/pilosus/dienstplan/
repo_name: GitHub

strict: true

theme:
  name: material
  language: en

plugins:
  - search:
      lang: en

extra:
  alternate:
    - name: English
      link: /
      lang: en

nav:
  - Getting started: index.md
  - Installation: install.md
  - Usage: usage.md
