application:
  name: "dienstplan"
  version: !envvar [APP__VERSION, latest]
  env: !envvar [APP__ENV, production]
  debug: !envvar [APP__DEBUG, false]

server:
  port: !envvar [SERVER__PORT, 8080]
  loglevel: !envvar [SERVER__LOGLEVEL, INFO]
  access-log: !envvar [SERVER__ACCESS_LOG, true]
  block-thread: !envvar [SERVER__BLOCK_THREAD, true]

slack:
  token: !envvar SLACK__TOKEN
  sign: !envvar SLACK__SIGN

alerts:
  sentry: !envvar ALERTS__SENTRY_DSN

db:
  adapter: "postgresql"
  server-name: !envvar DB__SERVER_NAME
  port-number: !envvar [DB__PORT_NUMBER, 5432]
  database-name: !envvar DB__DATABASE_NAME
  username: !envvar DB__USERNAME
  password: !envvar DB__PASSWORD
  minimum-idle: !envvar [DB__POOL_MIN_IDLE, 10]
  maximum-pool-size: !envvar [DB__POOL_MAX_SIZE, 20]
  connection-timeout: !envvar [DB__TIMEOUT_MS_CONNECTION, 10000]
