application:
  name: "dienstplan"
  version: !envvar APP__VERSION
  env: !envvar APP__ENV
  debug: !envvar APP__DEBUG

server:
  port: !envvar [SERVER__PORT, 8080]
  loglevel: !envvar SERVER__LOGLEVEL
  access-log: "true"

slack:
  token: !envvar SLACK__TOKEN
  sign: !envvar SLACK__SIGN

alerts:
  sentry: !envvar ALERTS__SENTRY_DSN

db:
  adapter: "postgresql"
  server-name: !envvar DB__SERVER_NAME
  port-number: !envvar [DB__PORT_NUMBER, 5432]
  database-name: !envvar DB__DATABASE_NAME
  username: !envvar DB__USERNAME
  password: !envvar DB__PASSWORD
  minimum-idle: 10
  maximum-pool-size: 20
  connection-timeout: 10000
